apiVersion: v1
kind: Service
metadata:
  name: remails-management
  annotations:
    service.beta.kubernetes.io/upcloud-load-balancer-config: |
      {
        "plan": {{ .Values.management.load_balancer_plan | quote }},
        "frontends": [{
          "name": "http",
          "mode": "http",
          "port": 80,
          "rules": [
            {
              "name": "redirect-to-https",
              "priority": 100,
              "matchers": [],
              "actions": [
                {
                  "type": "http_redirect",
                  "action_http_redirect": {
                    "scheme": "https"
                  }
                }
              ]
            }
          ]
        },
        {
          "name": "https",
          "mode": "http",
          "port": 443,
          "tls_configs": [
            {
               "name": {{ .Values.management.certificate_bundle_name | quote }},
               "certificate_bundle_uuid": {{ .Values.management.certificate_bundle_uuid | quote }}
            }
          ]
        }]
      }
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: remails-management
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: https
      protocol: TCP
      port: 443
      targetPort: http
  type: LoadBalancer
  