apiVersion: v1
kind: Secret
metadata:
  name: secrets
stringData:
  database_url: {{ .Values.database_url | quote }}
  session_key: {{ .Values.session_key | quote }}
  github_client_secret: {{ .Values.github_oauth.client_secret | quote }}