apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: remails-{{ .Values.environment }}
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ printf "letsencrypt-%s-http" .Values.management.certificate_type }}
    traefik.ingress.kubernetes.io/router.middlewares: "{{ .Release.Namespace }}-remails-redirect-middleware@kubernetescrd"
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.management.server_name }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: management
                port:
                  name: http
    - host: www.{{ .Values.management.server_name }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: management
                port:
                  name: http
  tls:
    - hosts:
        - {{ .Values.management.server_name }}
        - www.{{ .Values.management.server_name }}
      secretName: management-tls-cert-traefik
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: remails-redirect-middleware
  namespace: {{ .Release.Namespace }}
spec:
  redirectRegex:
    regex: "^https?://www.{{ .Values.management.server_name }}/(.*)"
    replacement: "https://{{ .Values.management.server_name }}/${1}"
    permanent: true
